import {
  Body,
  Controller,
  HttpCode,
  HttpStatus,
  Logger,
  Post,
  Request,
  UseGuards,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Between, DataSource, EntityManager, In, Repository } from 'typeorm';
import { ScheduleGeneratorService, GenerationInput } from '../../domain/schedule-generator.service';
import {
  GeneratePlanDto,
  GenerateScheduleDto,
  RescheduleConflictsDto,
  ValidateConstraintsDto,
  ScoreSlotDto,
  CheckConflictsDto,
  ApplyConflictsDto,
} from './dto/scheduler.dto';
import {
  GeneratePlanResponse,
  GenerateScheduleResponse,
  RescheduleConflictsResponse,
  ValidateConstraintsResponse,
  ScoreSlotResponse,
  CheckConflictsResponse,
  ApplyConflictsResponse,
  ConflictSuggestionDto,
} from './dto/scheduler.response';
import { ConstraintCheckerService } from '../../domain/constraint-checker.service';
import { ScoringEngineService } from '../../domain/scoring-engine.service';
import {
  CalendarEvent as SchedulerCalendarEvent,
  DEFAULT_SETTINGS,
  DEFAULT_WEEK_CONTEXT,
  SchedulerSettings as SchedulerSettingsModel,
  WeekContext,
  Workout,
  WorkoutType,
} from '../../shared/models';
import { JwtAuthGuard } from '../../auth/jwt-auth.guard';
import { TrainingPlanService } from '../../training-plan/training-plan.service';
import { SchedulerSettingsService } from '../../scheduler-settings/scheduler-settings.service';
import { CycleProfileService } from '../../cycle-profile/cycle-profile.service';
import { CalendarEvent } from '../../calendar-event/calendar-event.entity';
import { PlannedSession } from '../../planned-session/planned-session.entity';
import { SchedulerSettings } from '../../scheduler-settings/scheduler-settings.entity';

@Controller('scheduler')
@UseGuards(JwtAuthGuard)
export class SchedulerController {
  private readonly logger = new Logger(SchedulerController.name);

  constructor(
    private readonly scheduleGenerator: ScheduleGeneratorService,
    private readonly constraintChecker: ConstraintCheckerService,
    private readonly scoringEngine: ScoringEngineService,
    private readonly trainingPlanService: TrainingPlanService,
    private readonly schedulerSettingsService: SchedulerSettingsService,
    private readonly cycleProfileService: CycleProfileService,
    private readonly dataSource: DataSource,
    @InjectRepository(CalendarEvent)
    private readonly calendarEventRepository: Repository<CalendarEvent>,
    @InjectRepository(PlannedSession)
    private readonly plannedSessionRepository: Repository<PlannedSession>,
  ) {}

  /**
   * Generate optimal schedule based on inputs
   * POST /api/v1/scheduler/generate
   */
  @Post('generate')
  @HttpCode(HttpStatus.OK)
  async generate(@Request() req, @Body() dto: GenerateScheduleDto): Promise<GenerateScheduleResponse> {
    const userId = req.user.userId as string;
    const range = this.resolveDateRangeFromEvents(dto.existingEvents);

    if (range) {
      await this.dataSource.transaction(async (manager) => {
        await this.cleanupAutoGeneratedEventsInRange(manager, userId, range.startDate, range.endDate);
      });
    }

    let weekContext: WeekContext = dto.weekContext ?? { ...DEFAULT_WEEK_CONTEXT };
    if (!weekContext.cyclePhasesByDay && range) {
      const cycleData = await this.cycleProfileService.computePhasesForWeek(userId, range.startDate);
      weekContext = {
        ...weekContext,
        cyclePhasesByDay: cycleData.phasesByDay,
        cycleConfidence: cycleData.confidence,
        cycleTrackingEnabled: cycleData.trackingEnabled,
      };
    }

    const input: GenerationInput = {
      existingEvents: dto.existingEvents,
      workouts: dto.workouts,
      mealPrep: dto.mealPrep,
      settings: dto.settings,
      weekContext,
    };

    const result = this.scheduleGenerator.generate(input);

    return {
      placedEvents: result.placedEvents,
      unplacedWorkouts: result.unplacedWorkouts,
      totalScore: result.totalScore,
      placedWorkoutCount: result.placedWorkoutCount,
      placedLongWorkoutCount: result.placedLongWorkoutCount,
      weightedWorkoutScore: result.weightedWorkoutScore,
    };
  }

  @Post('generate-plan')
  @HttpCode(HttpStatus.OK)
  async generatePlan(
    @Request() req,
    @Body() dto: GeneratePlanDto,
  ): Promise<GeneratePlanResponse> {
    const userId = req.user.userId as string;
    const plan = await this.trainingPlanService.findOneByUser(dto.planId, userId);
    const [recurringShiftTemplates, schedulerSettings] = await Promise.all([
      this.loadRecurringShifts(userId),
      this.schedulerSettingsService.findByUser(userId).then((s) => this.toSchedulerSettings(s)),
    ]);
    this.markScheduledSessionsPending(plan);
    return this.schedulePendingWeeks({
      userId,
      plan,
      recurringShiftTemplates,
      schedulerSettings,
      resetExisting: true,
    });
  }

  @Post('reschedule-conflicts')
  @HttpCode(HttpStatus.OK)
  async rescheduleConflicts(
    @Request() req,
    @Body() dto: RescheduleConflictsDto,
  ): Promise<RescheduleConflictsResponse> {
    const userId = req.user.userId as string;
    const plan = await this.trainingPlanService.findOneByUser(dto.planId, userId);
    const [recurringShiftTemplates, schedulerSettings] = await Promise.all([
      this.loadRecurringShifts(userId),
      this.schedulerSettingsService.findByUser(userId).then((s) => this.toSchedulerSettings(s)),
    ]);
    this.markScheduledSessionsPending(plan);
    const affectedWeeks = [...(plan.weeks ?? [])]
      .map((week) => week.weekNumber)
      .sort((a, b) => a - b);

    const rescheduled = await this.schedulePendingWeeks({
      userId,
      plan,
      recurringShiftTemplates,
      schedulerSettings,
      resetExisting: true,
    });

    return {
      conflictsFound: 0,
      weeksRescheduled: rescheduled.scheduledWeeks,
      workoutsRescheduled: rescheduled.totalEventsPlaced,
      affectedWeeks,
    };
  }

  /**
   * Validate if a specific slot violates hard constraints
   * POST /api/v1/scheduler/validate
   */
  @Post('validate')
  @HttpCode(HttpStatus.OK)
  validate(@Body() dto: ValidateConstraintsDto): ValidateConstraintsResponse {
    const settings = dto.settings ?? DEFAULT_SETTINGS;
    const weekContext = dto.weekContext ?? DEFAULT_WEEK_CONTEXT;

    const shifts = dto.existingEvents.filter((e) => e.type === 'shift');
    const alreadyPlaced = dto.existingEvents.filter(
      (e) => e.type === 'workout' || e.type === 'mealprep' || e.type === 'custom-event',
    );

    const ctx = {
      shifts,
      weekContext,
      settings,
      alreadyPlaced,
      minDaysBetweenMealPrepSessions: dto.minDaysBetweenMealPrepSessions ?? 1,
    };

    const isViolation = this.constraintChecker.isHardViolation(
      dto.day,
      dto.startMin,
      dto.endMin,
      dto.type,
      dto.workout ?? null,
      ctx,
    );

    const violations: string[] = [];
    if (isViolation) {
      violations.push('Slot violates one or more hard constraints');
    }

    return {
      isValid: !isViolation,
      violations,
    };
  }

  /**
   * Detect conflicts for a new/edited event and suggest resolutions
   * POST /api/v1/scheduler/check-conflicts
   */
  @Post('check-conflicts')
  @HttpCode(HttpStatus.OK)
  async checkConflicts(
    @Request() req,
    @Body() dto: CheckConflictsDto,
  ): Promise<CheckConflictsResponse> {
    const userId = req.user.userId as string;
    const { event, excludeEventId } = dto;
    const eventDate = event.date;

    const [rangeEvents, repeatShifts, rawSettings] = await Promise.all([
      this.calendarEventRepository.find({
        where: [
          { userId, isRepeatingWeekly: false, date: this.shiftDate(eventDate, -1) },
          { userId, isRepeatingWeekly: false, date: eventDate },
          { userId, isRepeatingWeekly: false, date: this.shiftDate(eventDate, 1) },
        ],
      }),
      this.loadRecurringShifts(userId),
      this.schedulerSettingsService.findByUser(userId),
    ]);

    const earliestMin = this.toMinutes(rawSettings?.autoPlaceEarliestTime ?? '06:00');
    const latestMin = this.toMinutes(rawSettings?.autoPlaceLatestTime ?? '22:00');

    const commute = event.commuteMinutes ?? 0;
    const evStartMin = this.toMinutes(event.startTime);
    const evEndMin = this.toMinutes(event.endTime);
    const bufferStart = event.type === 'shift' ? Math.max(0, evStartMin - commute) : evStartMin;
    const bufferEnd = event.type === 'shift' ? Math.min(1440, evEndMin + commute) : evEndMin;

    const sameDayWorkouts = rangeEvents.filter(
      (e) =>
        e.date === eventDate &&
        e.id !== excludeEventId &&
        e.type === 'workout' &&
        !e.isManuallyPlaced &&
        this.toMinutes(e.startTime) < bufferEnd &&
        this.toMinutes(e.endTime) > bufferStart,
    );

    // Protect completed sessions — look up by linkedCalendarEventId
    const workoutIds = sameDayWorkouts.map((w) => w.id);
    const completedEventIds = new Set<string>();
    if (workoutIds.length > 0) {
      const linkedSessions = await this.plannedSessionRepository.find({
        where: { linkedCalendarEventId: In(workoutIds) },
        select: ['linkedCalendarEventId', 'status'],
      });
      for (const s of linkedSessions) {
        if (s.status === 'completed' && s.linkedCalendarEventId) {
          completedEventIds.add(s.linkedCalendarEventId);
        }
      }
    }

    const toProcess = sameDayWorkouts
      .filter((w) => !completedEventIds.has(w.id))
      .slice(0, 2); // max 2 per spec

    const conflicts: ConflictSuggestionDto[] = toProcess.map((workout) => ({
      eventId: workout.id,
      title: workout.title,
      day: workout.day,
      date: workout.date ?? eventDate,
      startTime: workout.startTime,
      endTime: workout.endTime,
      priority: workout.priority ?? 'supporting',
      isManuallyPlaced: workout.isManuallyPlaced ?? false,
      suggestion: this.generateConflictSuggestion(
        workout,
        rangeEvents,
        repeatShifts,
        event,
        earliestMin,
        latestMin,
      ),
    }));

    return { hasConflicts: conflicts.length > 0, conflicts };
  }

  /**
   * Apply accepted conflict resolutions — batch-move calendar events
   * POST /api/v1/scheduler/apply-conflicts
   */
  @Post('apply-conflicts')
  @HttpCode(HttpStatus.OK)
  async applyConflicts(
    @Request() req,
    @Body() dto: ApplyConflictsDto,
  ): Promise<ApplyConflictsResponse> {
    const userId = req.user.userId as string;
    const moveIds = dto.moves.map((m) => m.eventId);

    const completedEventIds = new Set<string>();
    if (moveIds.length > 0) {
      const linked = await this.plannedSessionRepository.find({
        where: { linkedCalendarEventId: In(moveIds) },
        select: ['linkedCalendarEventId', 'status'],
      });
      for (const s of linked) {
        if (s.status === 'completed' && s.linkedCalendarEventId) {
          completedEventIds.add(s.linkedCalendarEventId);
        }
      }
    }

    let moved = 0;
    await this.dataSource.transaction(async (manager) => {
      const repo = manager.getRepository(CalendarEvent);
      for (const move of dto.moves) {
        if (completedEventIds.has(move.eventId)) continue;
        const newDay = this.dayIndexFromDate(move.newDate);
        await repo.update(
          { id: move.eventId, userId },
          { day: newDay, date: move.newDate, startTime: move.newStartTime, endTime: move.newEndTime },
        );
        moved++;
      }
    });

    return { moved };
  }

  /**
   * Score a specific time slot
   * POST /api/v1/scheduler/score
   */
  @Post('score')
  @HttpCode(HttpStatus.OK)
  score(@Body() dto: ScoreSlotDto): ScoreSlotResponse {
    const settings = dto.settings ?? DEFAULT_SETTINGS;
    const weekContext = dto.weekContext ?? DEFAULT_WEEK_CONTEXT;

    const shifts = dto.existingEvents.filter((e) => e.type === 'shift');
    const alreadyPlaced = dto.existingEvents.filter(
      (e) => e.type === 'workout' || e.type === 'mealprep' || e.type === 'custom-event',
    );

    const ctx = {
      shifts,
      weekContext,
      settings,
      alreadyPlaced,
      candidateWorkout: dto.candidateWorkout
        ? {
            workoutType: dto.candidateWorkout.workoutType as WorkoutType | undefined,
            isLongEndurance: dto.candidateWorkout.isLongEndurance,
            durationMinutes: dto.candidateWorkout.durationMinutes,
            sessionType: dto.candidateWorkout.sessionType,
            type: dto.candidateWorkout.type,
          }
        : undefined,
      totalWorkoutsNeeded: dto.totalWorkoutsNeeded,
    };

    const totalScore = this.scoringEngine.score(dto.day, dto.startMin, dto.endMin, dto.type, ctx);

    return {
      score: totalScore,
    };
  }

  private expandRepeatingShiftsForRange(
    shifts: CalendarEvent[],
    weekStartDate: string,
    startOffset: number,
    endOffset: number,
  ): SchedulerCalendarEvent[] {
    const events: SchedulerCalendarEvent[] = [];

    for (let offset = startOffset; offset <= endOffset; offset++) {
      const date = this.shiftDate(weekStartDate, offset);
      const weekday = this.dayIndexFromDate(date);

      for (const shift of shifts) {
        if (shift.day !== weekday) {
          continue;
        }

        events.push({
          id: shift.id,
          title: shift.title,
          type: 'shift',
          day: offset,
          date,
          startTime: shift.startTime,
          endTime: shift.endTime,
          durationMinutes: shift.durationMinutes ?? undefined,
          shiftType: shift.shiftType ?? undefined,
          commuteMinutes: shift.commuteMinutes ?? undefined,
          isLocked: shift.isLocked,
          isPersonal: shift.isPersonal,
          isRepeatingWeekly: true,
        });
      }
    }

    return events;
  }

  private toSchedulerEvent(
    event: CalendarEvent,
    linkedSession: PlannedSession | null,
    weekStartDate: string,
  ): SchedulerCalendarEvent {
    const day = event.date ? this.dayOffsetFromWeekStart(weekStartDate, event.date) : event.day;
    const type = event.isPersonal ? 'custom-event' : event.type;

    return {
      id: event.id,
      title: event.title,
      type,
      day,
      date: event.date,
      startTime: event.startTime,
      endTime: event.endTime,
      durationMinutes: event.durationMinutes ?? undefined,
      commuteMinutes: event.commuteMinutes ?? undefined,
      workoutType: linkedSession ? this.mapSessionTypeToWorkoutType(linkedSession.sessionType) : undefined,
      distanceKm: linkedSession?.distanceTarget ?? undefined,
      distanceCountsAsLong: linkedSession?.sessionType === 'long_run',
      isLocked: event.isLocked,
      isPersonal: event.isPersonal,
      isRepeatingWeekly: event.isRepeatingWeekly,
      sessionType: linkedSession?.sessionType ?? undefined,
      plannedSessionId: linkedSession?.id ?? undefined,
    };
  }

  private toWorkout(session: PlannedSession): Workout {
    return {
      id: session.id,
      name: this.formatSessionName(session.sessionType),
      workoutType: this.mapSessionTypeToWorkoutType(session.sessionType),
      duration: session.duration,
      frequencyPerWeek: 1,
      priority: session.priority,
      distanceKm: session.distanceTarget ?? undefined,
      distanceCountsAsLong: session.sessionType === 'long_run',
      intensity: session.intensity,
      cyclePhaseRules: session.cyclePhaseRules ?? undefined,
    };
  }

  private toSchedulerSettings(settings: SchedulerSettings): SchedulerSettingsModel {
    return {
      commuteMinutes: settings.afterShiftBufferMinutes ?? 0,
      autoPlaceEarliestTime: settings.autoPlaceEarliestTime ?? '06:00',
      autoPlaceLatestTime: settings.autoPlaceLatestTime ?? '22:00',
      preferredWorkoutTimes: settings.preferredWorkoutTimes ?? [],
      enduranceWeight: settings.enduranceWeight,
      strengthWeight: settings.strengthWeight,
      yogaWeight: settings.yogaWeight,
      enduranceThresholds: {
        running: { durationMin: settings.enduranceWorkoutMinDuration, distanceKm: settings.runningDistanceThreshold ?? 15 },
        biking: { durationMin: Math.max(90, settings.enduranceWorkoutMinDuration), distanceKm: settings.bikingDistanceThreshold ?? 40 },
        swimming: { durationMin: settings.enduranceWorkoutMinDuration, distanceKm: settings.swimmingDistanceThreshold ?? 3 },
      },
      enduranceRestDays: settings.enduranceRestDays ?? 1,
      priorityHierarchy: ['sport', 'recovery', 'mealprep'],
    };
  }

  private async schedulePendingWeeks(params: {
    userId: string;
    plan: Awaited<ReturnType<TrainingPlanService['findOneByUser']>>;
    recurringShiftTemplates: CalendarEvent[];
    schedulerSettings: SchedulerSettingsModel;
    weekFilter?: Set<number>;
    resetExisting?: boolean;
  }): Promise<GeneratePlanResponse> {
    const { userId, plan, recurringShiftTemplates, schedulerSettings, weekFilter, resetExisting } = params;
    const sortedWeeks = [...(plan.weeks ?? [])].sort((a, b) => a.weekNumber - b.weekNumber);
    const unplacedSessions: GeneratePlanResponse['unplacedSessions'] = [];
    let scheduledWeeks = 0;
    let totalEventsPlaced = 0;

    await this.dataSource.transaction(async (manager) => {
      const transactionEventRepository = manager.getRepository(CalendarEvent);
      const transactionSessionRepository = manager.getRepository(PlannedSession);

      if (resetExisting) {
        await this.resetScheduledEventsForPlan(manager, userId, plan, weekFilter);
      }

      const weeksToProcess = sortedWeeks.filter((w) => !weekFilter || weekFilter.has(w.weekNumber));
      if (weeksToProcess.length === 0) {
        return;
      }

      const planStartDate = weeksToProcess[0].startDate;
      const planEndDate = weeksToProcess[weeksToProcess.length - 1].endDate;
      const prevDates = weeksToProcess.map((w) => this.shiftDate(w.startDate, -1));

      const [allOneTimeEvents, allPrevWorkouts] = await Promise.all([
        transactionEventRepository.find({
          where: { userId, isRepeatingWeekly: false, date: Between(planStartDate, planEndDate) },
          order: { date: 'ASC', startTime: 'ASC' },
        }),
        transactionEventRepository.find({
          where: { userId, isRepeatingWeekly: false, type: 'workout', date: In(prevDates) },
          order: { startTime: 'ASC' },
        }),
      ]);

      for (const week of weeksToProcess) {
        const pendingSessions = (week.sessions ?? []).filter((session) => session.status === 'pending');
        if (pendingSessions.length === 0) {
          continue;
        }

        scheduledWeeks += 1;

        const previousWeekEndDate = this.shiftDate(week.startDate, -1);
        const oneTimeEvents = allOneTimeEvents.filter((e) => !!e.date && e.date >= week.startDate && e.date <= week.endDate);
        const previousWeekEndWorkouts = allPrevWorkouts.filter((e) => e.date === previousWeekEndDate);

        const sessionsByLinkedEventId = new Map(
          (week.sessions ?? [])
            .filter((session) => !!session.linkedCalendarEventId)
            .map((session) => [session.linkedCalendarEventId as string, session]),
        );

        const existingEvents = [
          ...this.expandRepeatingShiftsForRange(recurringShiftTemplates, week.startDate, 0, 6),
          ...oneTimeEvents.map((event) =>
            this.toSchedulerEvent(event, sessionsByLinkedEventId.get(event.id) ?? null, week.startDate),
          ),
        ];

        const cycleData = await this.cycleProfileService.computePhasesForWeek(userId, week.startDate);
        const weekContext = {
          ...DEFAULT_WEEK_CONTEXT,
          previousWeekEndedWithWorkout: previousWeekEndWorkouts.length > 0,
          cyclePhasesByDay: cycleData.phasesByDay,
          cycleConfidence: cycleData.confidence,
          cycleTrackingEnabled: cycleData.trackingEnabled,
        };

        const generationInput: GenerationInput = {
          existingEvents,
          workouts: pendingSessions.map((session) => this.toWorkout(session)),
          mealPrep: {
            duration: 90,
            sessionsPerWeek: 0,
          },
          settings: schedulerSettings,
          weekContext,
        };

        const result = this.scheduleGenerator.generate(generationInput);
        const dedupedPlacedEvents: typeof result.placedEvents = [];
        const seenSessionIds = new Set<string>();

        for (const event of result.placedEvents) {
          if (event.plannedSessionId) {
            if (seenSessionIds.has(event.plannedSessionId)) {
              continue;
            }
            seenSessionIds.add(event.plannedSessionId);
          }

          dedupedPlacedEvents.push(event);
        }

        let placedEvents = dedupedPlacedEvents;
        if (placedEvents.length > pendingSessions.length) {
          this.logger.warn(
            `Week ${week.weekNumber} generated ${placedEvents.length} events for ${pendingSessions.length} planned sessions. Truncating to prevent duplicates.`,
          );
          placedEvents = placedEvents.slice(0, pendingSessions.length);
        }

        const eventEntities = placedEvents.map((event) => {
          const linkedSession = pendingSessions.find((s) => s.id === event.plannedSessionId);
          return transactionEventRepository.create({
            userId,
            title: event.title,
            type: event.type === 'mealprep' ? 'mealprep' : 'workout',
            day: event.day,
            date: this.dateForWeekday(week.startDate, event.day),
            startTime: event.startTime,
            endTime: event.endTime,
            durationMinutes: event.durationMinutes ?? undefined,
            isManuallyPlaced: false,
            isLocked: false,
            isPersonal: false,
            isRepeatingWeekly: false,
            priority: linkedSession?.priority,
          });
        });

        const createdEvents = eventEntities.length > 0 ? await transactionEventRepository.save(eventEntities) : [];

        totalEventsPlaced += createdEvents.length;

        const createdEventBySessionId = new Map(
          createdEvents.map((event, index) => [placedEvents[index]?.plannedSessionId, event]),
        );

        for (const session of pendingSessions) {
          const createdEvent = createdEventBySessionId.get(session.id);
          if (!createdEvent) {
            continue;
          }

          session.status = 'scheduled';
          session.linkedCalendarEventId = createdEvent.id;
        }

        await transactionSessionRepository.save(
          pendingSessions.filter((session) => session.status === 'scheduled'),
        );

        for (const unplaced of result.unplacedWorkouts) {
          unplacedSessions.push({
            weekNumber: week.weekNumber,
            sessionName: unplaced.workoutName,
            reason: unplaced.reason,
          });
        }
      }
    });

    return {
      scheduledWeeks,
      totalEventsPlaced,
      unplacedSessions,
    };
  }

  private markScheduledSessionsPending(
    plan: Awaited<ReturnType<TrainingPlanService['findOneByUser']>>,
    weekFilter?: Set<number>,
  ): void {
    for (const week of plan.weeks ?? []) {
      if (weekFilter && !weekFilter.has(week.weekNumber)) {
        continue;
      }

      for (const session of week.sessions ?? []) {
        if (session.status === 'scheduled' || session.status === 'moved') {
          session.status = 'pending';
          session.linkedCalendarEventId = null;
        }
      }
    }
  }

  private async resetScheduledEventsForPlan(
    manager: EntityManager,
    userId: string,
    plan: Awaited<ReturnType<TrainingPlanService['findOneByUser']>>,
    weekFilter?: Set<number>,
  ): Promise<void> {
    const targetWeeks = [...(plan.weeks ?? [])]
      .filter((week) => !weekFilter || weekFilter.has(week.weekNumber))
      .sort((a, b) => a.weekNumber - b.weekNumber);

    if (targetWeeks.length === 0) {
      return;
    }

    const weekIds = targetWeeks.map((week) => week.id);
    const startDate = targetWeeks[0].startDate;
    const endDate = targetWeeks[targetWeeks.length - 1].endDate;

    await manager
      .getRepository(CalendarEvent)
      .createQueryBuilder()
      .delete()
      .from(CalendarEvent)
      .where('"userId" = :userId', { userId })
      .andWhere('type IN (:...types)', { types: ['workout', 'mealprep'] })
      .andWhere('"isRepeatingWeekly" = false')
      .andWhere('COALESCE("isManuallyPlaced", false) = false')
      .andWhere('date BETWEEN :startDate AND :endDate', { startDate, endDate })
      .andWhere(
        `"id" NOT IN (
          SELECT ps."linkedCalendarEventId"
          FROM planned_sessions ps
          WHERE ps."linkedCalendarEventId" IS NOT NULL
          AND ps."status" = :completedStatus
        )`,
        { completedStatus: 'completed' },
      )
      .execute();

    await manager
      .getRepository(PlannedSession)
      .createQueryBuilder()
      .update(PlannedSession)
      .set({
        status: 'pending',
        linkedCalendarEventId: null,
      })
      .where('"planWeekId" IN (:...weekIds)', { weekIds })
      .andWhere('status IN (:...statuses)', { statuses: ['scheduled', 'moved'] })
      .andWhere(
        `"linkedCalendarEventId" IS NULL OR "linkedCalendarEventId" NOT IN (
          SELECT ps."linkedCalendarEventId"
          FROM planned_sessions ps
          WHERE ps."linkedCalendarEventId" IS NOT NULL
          AND ps."status" = :completedStatus
        )`,
        { completedStatus: 'completed' },
      )
      .execute();
  }

  private resolveDateRangeFromEvents(events: SchedulerCalendarEvent[]): { startDate: string; endDate: string } | null {
    const dated = events
      .map((event) => event.date)
      .filter((value): value is string => !!value)
      .sort();

    if (dated.length === 0) {
      return null;
    }

    return {
      startDate: dated[0],
      endDate: dated[dated.length - 1],
    };
  }

  private async cleanupAutoGeneratedEventsInRange(
    manager: EntityManager,
    userId: string,
    startDate: string,
    endDate: string,
  ): Promise<void> {
    await manager
      .getRepository(CalendarEvent)
      .createQueryBuilder()
      .delete()
      .from(CalendarEvent)
      .where('"userId" = :userId', { userId })
      .andWhere('type IN (:...types)', { types: ['workout', 'mealprep'] })
      .andWhere('"isRepeatingWeekly" = false')
      .andWhere('COALESCE("isManuallyPlaced", false) = false')
      .andWhere('date BETWEEN :startDate AND :endDate', { startDate, endDate })
      .andWhere(
        `"id" NOT IN (
          SELECT ps."linkedCalendarEventId"
          FROM planned_sessions ps
          WHERE ps."linkedCalendarEventId" IS NOT NULL
          AND ps."status" = :completedStatus
        )`,
        { completedStatus: 'completed' },
      )
      .execute();
  }

  private async loadRecurringShifts(userId: string): Promise<CalendarEvent[]> {
    return this.calendarEventRepository.find({
      where: { userId, isRepeatingWeekly: true, type: 'shift' },
      order: { day: 'ASC', startTime: 'ASC' },
    });
  }

  private overlapsShiftWithCommute(
    workoutEvent: CalendarEvent,
    shift: CalendarEvent,
    defaultCommuteMinutes: number,
  ): boolean {
    const workoutStart = this.toMinutes(workoutEvent.startTime);
    const workoutEnd = this.toMinutes(workoutEvent.endTime);
    const shiftStart = this.toMinutes(shift.startTime);
    const shiftEnd = this.toMinutes(shift.endTime);
    const commute = shift.commuteMinutes ?? defaultCommuteMinutes ?? 0;

    const blockedStart = Math.max(0, shiftStart - commute);
    const blockedEnd = Math.min(24 * 60, shiftEnd + commute);

    return workoutStart < blockedEnd && workoutEnd > blockedStart;
  }

  private toMinutes(value: string): number {
    const [hours, minutes] = value.split(':').map(Number);
    return hours * 60 + minutes;
  }

  private formatSessionName(sessionType: string): string {
    const normalized = sessionType.toLowerCase();
    const labelMap: Record<string, string> = {
      easy_run: 'Easy Run',
      long_run: 'Long Run',
      tempo: 'Tempo Run',
      intervals: 'Intervals',
      hill_reps: 'Hill Reps',
      cardio_run: 'Cardio Run',
      strength: 'Strength Training',
      hiit: 'HIIT',
      yoga: 'Yoga',
      mobility: 'Mobility',
      swim: 'Swim',
      bike: 'Bike',
    };

    return labelMap[normalized] ?? normalized.replace(/_/g, ' ').replace(/\b\w/g, (char) => char.toUpperCase());
  }

  private static readonly SESSION_TYPE_WORKOUT_MAP: Record<string, WorkoutType> = {
    easy_run: 'running',
    long_run: 'running',
    tempo: 'running',
    intervals: 'running',
    hill_reps: 'running',
    cardio_run: 'running',
    strength: 'strength',
    hiit: 'strength',
    yoga: 'yoga',
    mobility: 'yoga',
    swim: 'swimming',
    bike: 'biking',
  };

  private mapSessionTypeToWorkoutType(sessionType: string): WorkoutType {
    return SchedulerController.SESSION_TYPE_WORKOUT_MAP[sessionType.toLowerCase()] ?? 'strength';
  }

  private dayIndexFromDate(date: string): number {
    const parsed = new Date(`${date}T00:00:00`);
    return (parsed.getDay() + 6) % 7;
  }

  private dateForWeekday(weekStartDate: string, dayIndex: number): string {
    return this.shiftDate(weekStartDate, dayIndex);
  }

  private dayOffsetFromWeekStart(weekStartDate: string, date: string): number {
    const start = new Date(`${weekStartDate}T00:00:00`);
    const target = new Date(`${date}T00:00:00`);
    const millisecondsPerDay = 24 * 60 * 60 * 1000;
    return Math.round((target.getTime() - start.getTime()) / millisecondsPerDay);
  }

  private shiftDate(date: string, offset: number): string {
    const value = new Date(`${date}T00:00:00`);
    value.setDate(value.getDate() + offset);
    return this.toDateString(value);
  }

  private toDateString(date: Date): string {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  }

  private formatTime(minutes: number): string {
    const h = Math.floor(minutes / 60);
    const m = minutes % 60;
    return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`;
  }

  private generateConflictSuggestion(
    workout: CalendarEvent,
    rangeEvents: CalendarEvent[],
    repeatShifts: CalendarEvent[],
    newEvent: CheckConflictsDto['event'],
    earliestMin: number,
    latestMin: number,
  ): ConflictSuggestionDto['suggestion'] {
    const workoutDate = workout.date!;
    const duration = workout.durationMinutes ?? 45;
    const originalStart = this.toMinutes(workout.startTime);

    const newEvStart = this.toMinutes(newEvent.startTime);
    const newEvEnd = this.toMinutes(newEvent.endTime);
    const commute = newEvent.commuteMinutes ?? 0;
    const newBufStart = newEvent.type === 'shift' ? Math.max(0, newEvStart - commute) : newEvStart;
    const newBufEnd = newEvent.type === 'shift' ? Math.min(1440, newEvEnd + commute) : newEvEnd;

    const getOccupied = (date: string): Array<[number, number]> => {
      const dow = this.dayIndexFromDate(date);
      const occupied: Array<[number, number]> = [];

      for (const e of rangeEvents) {
        if (e.date !== date || e.id === workout.id) continue;
        const buf = e.type === 'shift' ? (e.commuteMinutes ?? 0) : 0;
        occupied.push([Math.max(0, this.toMinutes(e.startTime) - buf), Math.min(1440, this.toMinutes(e.endTime) + buf)]);
      }

      for (const s of repeatShifts) {
        if (s.day !== dow) continue;
        const buf = s.commuteMinutes ?? 0;
        occupied.push([Math.max(0, this.toMinutes(s.startTime) - buf), Math.min(1440, this.toMinutes(s.endTime) + buf)]);
      }

      if (date === newEvent.date) {
        occupied.push([newBufStart, newBufEnd]);
      }

      return occupied;
    };

    const canPlace = (date: string, start: number, end: number): boolean => {
      if (start < earliestMin || end > latestMin) return false;
      return !getOccupied(date).some(([s, e]) => start < e && end > s);
    };

    for (const offset of [60, 90, 120, -60, -90]) {
      const start = originalStart + offset;
      const end = start + duration;
      if (canPlace(workoutDate, start, end)) {
        return {
          action: 'shift_time',
          suggestedDay: this.dayIndexFromDate(workoutDate),
          suggestedDate: workoutDate,
          suggestedStartTime: this.formatTime(start),
          suggestedEndTime: this.formatTime(end),
          reason: `Moved ${Math.abs(offset)} min ${offset > 0 ? 'later' : 'earlier'} to avoid overlap`,
        };
      }
    }

    const DAY_NAMES = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
    for (const dayOffset of [-1, 1]) {
      const adjDate = this.shiftDate(workoutDate, dayOffset);
      for (const start of [originalStart, 6 * 60, 7 * 60, 8 * 60, 17 * 60, 18 * 60, 19 * 60]) {
        const end = start + duration;
        if (canPlace(adjDate, start, end)) {
          const dayName = DAY_NAMES[this.dayIndexFromDate(adjDate)] ?? 'nearby day';
          return {
            action: 'move_day',
            suggestedDay: this.dayIndexFromDate(adjDate),
            suggestedDate: adjDate,
            suggestedStartTime: this.formatTime(start),
            suggestedEndTime: this.formatTime(end),
            reason: `Moved to ${dayName} at ${this.formatTime(start)}`,
          };
        }
      }
    }

    return { action: 'cannot_resolve', reason: 'No available slot found. Reschedule manually.' };
  }
}
